# Fall 2024 Data Science Track: Week 2 - Data Cleaning Exercise

## Packages, Packages, Packages!

Import *all* the things here! You need the standard stuff: `pandas` and `numpy`.

If you got more stuff you want to use, add them here too. 🙂

In [1]:
# Import here.
import pandas as pd
import numpy as np

## Introduction

With the packages out of the way, now you will be working with the following data sets:

* `food_coded.csv`: [Food choices](https://www.kaggle.com/datasets/borapajo/food-choices?select=food_coded.csv) from Kaggle
* `Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`: [Ask A Manager Salary Survey 2021 (Responses)](https://docs.google.com/spreadsheets/d/1IPS5dBSGtwYVbjsfbaMCYIWnOuRmJcbequohNxCyGVw/view?&gid=1625408792) as *Tab Separated Values (.tsv)* from Google Docs

Each one poses different challenges. But you’ll―of course―overcome them with what you learned in class! 😉

## Food Choices Data Set

### Load the Data

In [2]:
# Load the Food choices data set into a variable (e.g., df_food).

food_data_set_path = '../data/food_coded.csv'

df_food = pd.read_csv(food_data_set_path)

### Explore the Data

In [3]:
len(df_food)

125

How much data did you just load?

In [4]:
# Count by hand. (lol kidding)
df_food.shape

(125, 61)

What are the columns and their types in this data set?

In [12]:
# Show the column names and their types.
df_food.dtypes

GPA                     str
Gender                int64
breakfast             int64
calories_chicken      int64
calories_day        float64
                     ...
type_sports             str
veggies_day           int64
vitamins              int64
waffle_calories       int64
weight                  str
Length: 61, dtype: object

### Clean the Data

Perhaps we’d like to know more another day, but the team is really interested in just the relationship between calories (`calories_day`) and weight. …and maybe gender.

Can you remove the other columns?

In [43]:
# Remove ‘em.
cleaned_df = df_food[['calories_day', 'weight', 'Gender']]

What about `NaN`s? How many are there?

In [31]:
# Count ‘em.
cleaned_df.isna().sum()

calories_day    19
weight           2
Gender           0
dtype: int64

We gotta remove those `NaN`s―the entire row.

In [46]:
# Drop ‘em.
cleaned_df = cleaned_df.dropna()

But what about the weird non-numeric values in the column obviously meant for numeric data?

Notice the data type of that column from when you got the types of all the columns?

If only we could convert the column to a numeric type and drop the rows with invalid values. 🤔

In [55]:
# Fix that.
cleaned_df['weight'] = pd.to_numeric(cleaned_df['weight'], errors = 'coerce')

cleaned_df = cleaned_df.dropna()
cleaned_df.head()

   calories_day  weight  Gender  new_weight
1           3.0   155.0       1           1
4           2.0   190.0       1           1
5           3.0   190.0       1           1
6           3.0   180.0       2           1
7           3.0   137.0       1           1

Now this data seems reasonably clean for our purposes! 😁

Let’s save it somewhere to be shipped off to another teammate. 💾

In [56]:
# Savey save!
save_as = 'cal-weight-gender.csv'

cleaned_df.to_csv(save_as, index = False)

## Ask a Manager Salary Survey 2021 (Responses) Data Set

### Load the Data

In [4]:
# Load the Ask A Manager Salary Survey 2021 (Responses) data set into a variable (e.g., df_salary).
salary_survey_path = '../data/manager_salary_survey2021.tsv'
df_salary = pd.read_csv(salary_survey_path, sep='\t')

Was that hard? 🙃

#### rename the file to something that is better for all systems.  
* No spaces in filename (can use '_')
* all lower case

### Explore

You know the drill.

How much data did you just load?

In [4]:
# Count by hand. I’m dead serious.

len(df_salary)

28062

What are the columns and their types?

In [5]:
# Show the column names and their types.

df_salary.dtypes

Timestamp                                                                                                                                                                                                                                   str
How old are you?                                                                                                                                                                                                                            str
What industry do you work in?                                                                                                                                                                                                               str
Job title                                                                                                                                                                                                                                   str
If your job title needs additional context, please clarify here:                                                                                                                                                                            str
What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)        str
How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.                                          float64
Please indicate the currency                                                                                                                                                                                                                str
If "Other," please indicate the currency here:                                                                                                                                                                                              str
If your income needs additional context, please provide it here:                                                                                                                                                                            str
What country do you work in?                                                                                                                                                                                                                str
If you're in the U.S., what state do you work in?                                                                                                                                                                                           str
What city do you work in?                                                                                                                                                                                                                   str
How many years of professional work experience do you have overall?                                                                                                                                                                         str
How many years of professional work experience do you have in your field?                                                                                                                                                                   str
What is your highest level of education completed?                                                                                                                                                                                          str
What is your gender?                                                                                                                                                                                                                        str
What is your race? (Choose all that apply.)                                                                                                                                                                                                 str
dtype: object

Oh… Ugh! Give these columns easier names to work with first. 🙄

In [5]:
# Rename ‘em.
# Non-binding suggestions: timestamp, age, industry, title, title_context, salary, additional_compensation, currency, other_currency, salary_context, country, state, city, total_yoe, field_yoe, highest_education_completed	gender, race

df_salary = df_salary.rename(columns={'Timestamp': 'timestamp', 'How old are you?': 'age', 'What industry do you work in?': 'industry', 'Job title': 'title', 
                          'If your job title needs additional context, please clarify here:': 'title_context', "What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)": 'salary',
                          'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.': 'additional_compensation',
                          'Please indicate the currency': 'currency', 'If "Other," please indicate the currency here:': 'other_currency', 
                          'If your income needs additional context, please provide it here:': 'salary_context', 'What country do you work in?': 'country',
                          "If you're in the U.S., what state do you work in?": 'state', 
                          'What city do you work in?': 'city', 'How many years of professional work experience do you have overall?': 'total_yoe',
                          'How many years of professional work experience do you have in your field?': 'field_yoe', 
                          'What is your highest level of education completed?': 'highest_education_completed', 
                          'What is your gender?': 'gender', 'What is your race? (Choose all that apply.)': 'race'})

It’s a lot, and that should not have been easy. 😏

You’re going to have a gander at the computing/tech subset first because thats *your* industry. But first, what value corresponds to that `industry`?

In [6]:
# List the unique industries and a count of their instances.

df_salary.industry.value_counts()

industry
Computing or Tech                               4699
Education (Higher Education)                    2464
Nonprofits                                      2419
Health care                                     1896
Government and Public Administration            1889
                                                ...
Undergrad student                                  1
Concrete Construction                              1
I'm currently a student and don't have a job       1
Student                                            1
Wine & Spirits                                     1
Name: count, Length: 1219, dtype: int64

That value among the top 5 is what you’re looking for innit? Filter out all the rows not in that industry and save it into a new dataframe.

In [8]:
# Filtery filter. (Save it to a new variable, df_salary_tech.)

df_salary_tech = df_salary[df_salary['industry'] == 'Computing or Tech']

Do a sanity check to make sure that the only values you kept are the one you are filtered for.

In [9]:
# Sanity Check 
df_salary_tech.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,"If ""Other,"" please indicate the currency here:",salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
1,4/27/2021 11:02:22,25-34,Computing or Tech,Change & Internal Communications Manager,NaN,"54,600",4000.0,GBP,NaN,NaN,United Kingdom,NaN,Cambridge,8 - 10 years,5-7 years,College degree,Non-binary,White
8,4/27/2021 11:03:01,45-54,Computing or Tech,Systems Analyst,Data developer/ETL Developer,"112,000",10000.0,USD,NaN,NaN,US,Missouri,St. Louis,21 - 30 years,21 - 30 years,College degree,Woman,White
43,4/27/2021 11:04:04,25-34,Computing or Tech,Principal Software Engineer,NaN,"187,500",5000.0,USD,NaN,NaN,United States,Pennsylvania,Pittsburgh,8 - 10 years,5-7 years,College degree,Woman,White
44,4/27/2021 11:04:04,25-34,Computing or Tech,Intelligence Analyst,NaN,"110,000",20000.0,USD,NaN,"Around 20,000 a year in stock",USA,Virginia,"Arlington, VA",8 - 10 years,8 - 10 years,Master's degree,Man,White
46,4/27/2021 11:04:07,35-44,Computing or Tech,Mobile developer,NaN,"144,600",2500.0,USD,NaN,NaN,USA,Massachusetts,Boston,5-7 years,5-7 years,PhD,Woman,White

We are very interested in salary figures. But how many dollars 💵 is a euro 💶 or a pound 💷? That sounds like a problem for another day. 🫠

For now, let’s just look at U.S. dollars (`'USD'`).

In [10]:
# Filtery filter for just the jobs that pay in USD!
df_salary_usd = df_salary[df_salary['currency'] == 'USD']
df_salary_usd.head()

,timestamp,age,industry,title,title_context,salary,additional_compensation,currency,"If ""Other,"" please indicate the currency here:",salary_context,country,state,city,total_yoe,field_yoe,highest_education_completed,gender,race
0,4/27/2021 11:02:10,25-34,Education (Higher Education),Research and Instruction Librarian,NaN,"55,000",0.0,USD,NaN,NaN,United States,Massachusetts,Boston,5-7 years,5-7 years,Master's degree,Woman,White
2,4/27/2021 11:02:38,25-34,"Accounting, Banking & Finance",Marketing Specialist,NaN,"34,000",NaN,USD,NaN,NaN,US,Tennessee,Chattanooga,2 - 4 years,2 - 4 years,College degree,Woman,White
3,4/27/2021 11:02:41,25-34,Nonprofits,Program Manager,NaN,"62,000",3000.0,USD,NaN,NaN,USA,Wisconsin,Milwaukee,8 - 10 years,5-7 years,College degree,Woman,White
4,4/27/2021 11:02:42,25-34,"Accounting, Banking & Finance",Accounting Manager,NaN,"60,000",7000.0,USD,NaN,NaN,US,South Carolina,Greenville,8 - 10 years,5-7 years,College degree,Woman,White
5,4/27/2021 11:02:46,25-34,Education (Higher Education),Scholarly Publishing Librarian,NaN,"62,000",NaN,USD,NaN,NaN,USA,New Hampshire,Hanover,8 - 10 years,2 - 4 years,Master's degree,Man,White

What we really want know is how each U.S. city pays in tech. What value in `country` represents the United States of America?

In [14]:
# We did filter for USD, so if we do a count of each unique country in descending count order, the relevant value(s) should show up at the top.
df_salary_usd['country'].value_counts()

country
United States     8989
USA               7922
US                2606
United States      667
U.S.               580
                  ...
Saudi Arabia         1
LOUTRELAND           1
philippines          1
Myanmar              1
Burma                1
Name: count, Length: 229, dtype: int64

### Clean the Data

Well, we can’t get our answers with what we currently have, so you’ll have to make some changes.

Let’s not worry about anything below the first 5 values for now. Convert the top 5 to a single canonical value―say, `'US'`, which is nice and short.

In [20]:
# Replace them all with 'US'.
US_names = ['US']
cond_1 = ~df_salary_usd['country'].isin(US_names)
df_salary_usd['country'] = np.where(cond_1,'US', df_salary_usd['country'])

Have a look at the count of each unique country again now.

In [21]:
# Count again.
df_salary_usd['country'].value_counts()

country
US    23374
Name: count, dtype: int64

Did you notice anything interesting?

In [ ]:
# BONUS CREDIT: resolve [most of] those anomalous cases too without exhaustively taking every variant literally into account.

In [22]:

# BONUS CREDIT: if you’ve resolved it, let’s see how well you did by counting the number of instances of each unique value.

df_salary_usd['country'].value_counts()

country
US    23374
Name: count, dtype: int64

It’s looking good so far. Let’s find out the minimum, mean, and maximum (in that order) salary by state, sorted by the mean in descending order.

In [41]:
# Find the minimum, mean, and maximum salary in USD by U.S. state.

df_salary_usd.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

,min,mean,max
state,,,
"Alabama, South Carolina",5000000,5.000000e+06,5000000
"Michigan, Texas, Washington",340000,3.400000e+05,340000
"Indiana, Ohio",245000,2.450000e+05,245000
Alaska,27040,2.322751e+05,10000000
"Colorado, Nevada",190000,1.900000e+05,190000
...,...,...,...
"District of Columbia, Washington",35000,3.500000e+04,35000
"Alabama, California",29120,2.912000e+04,29120
"District of Columbia, Maryland, Pennsylvania, Virginia",27040,2.704000e+04,27040
"Maryland, New York",14000,1.400000e+04,14000
"Alabama, Alaska, Arizona",15,1.500000e+01,15

Well, pooh! We forgot that `salary` isn’t numeric. Something wrong must be fixed.

In [40]:
# Fix it.
df_salary_usd['salary'] = df_salary_usd['salary'].str.replace(',', '', regex=False).astype(int)

Let’s try that again.

In [ ]:
# Try it again. Yeah!

That did the trick! Now let’s narrow this to data 2021 and 2022 just because (lel). *(Hint: that timestamp column may not be a temporal type right now.)*

In [56]:
# Filter the data to within 2021, 2022, or 2023, saving the DataFrame to a new variable, and generate the summary again.
df_salary_usd_datetime = df_salary[df_salary['currency'] == 'USD'].copy()
df_salary_usd_datetime['timestamp'] = pd.to_datetime(df_salary_usd_datetime['timestamp'], errors='coerce')
df_salary_usd_datetime['salary'] = (df_salary_usd_datetime['salary'].str.replace(',', '', regex=False).astype(int))

needed_years = [2021, 2022, 2023]
df_salary_usd_datetime = df_salary_usd_datetime[df_salary_usd_datetime['timestamp'].dt.year.isin(needed_years)]

df_salary_usd_datetime.groupby('state')['salary'].agg(['min', 'mean', 'max']).sort_values('mean', ascending=False)

                                                       min      mean     max
state
Michigan, Texas, Washington                         340000  340000.0  340000
Indiana, Ohio                                       245000  245000.0  245000
Colorado, Nevada                                    190000  190000.0  190000
California, Montana                                 185000  185000.0  185000
California, Texas                                   185000  185000.0  185000
...                                                    ...       ...     ...
Delaware, Pennsylvania                               35000   35000.0   35000
District of Columbia, Washington                     35000   35000.0   35000
Alabama, California                                  29120   29120.0   29120
District of Columbia, Maryland, Pennsylvania, V...   27040   27040.0   27040
Maryland, New York                                   14000   14000.0   14000

[131 rows x 3 columns]

## Bonus

Clearly, we do not have enough data to produce useful figures for the level of specificity you’ve now reached. What do you notice about Delaware and West Virginia?

Let’s back out a bit and return to `df_salary` (which was the loaded data with renamed columns but *sans* filtering).

### Bonus #0

Apply the same steps as before to `df_salary`, but do not filter for any specific industry. Do perform the other data cleaning stuff, and get to a point where you can generate the minimum, mean, and maximum by state.

### Bonus #1

This time, format the table output nicely (*$12,345.00*) without modifying the values in the `DataFrame`. That is, `df_salary` should be identical before versus after running your code.

(*Hint: if you run into an error about `jinja2` perhaps you need to `pip install` something.*)

### Bonus #2

Filter out the non-single-states (e.g., `'California, Colorado'`) in the most elegant way possible (i.e., *not* by blacklisting all the bad values).

### Bonus #3

Show the quantiles instead of just minimum, mean, and maximum―say 0%, 5%, 25%, 50%, 75%, 95%, and 100%. Outliers may be deceiving.

Sort by whatever interests you―like say the *50th* percentile.

And throw in a count by state too. It would be interesting to know how many data points contribute to the figures for each state. (*Hint: your nice formatting from Bonus #1 might not work this time around.* 😜)